//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace exemploApp.Web.Reports.RegistroEvento {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("RelatorioRegistroEventoDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class RelatorioRegistroEventoDataSet : global::System.Data.DataSet {
        
        private RelatorioRegistroEventoDataSetDataTable tableRelatorioRegistroEventoDataSet;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public RelatorioRegistroEventoDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected RelatorioRegistroEventoDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RelatorioRegistroEventoDataSet"] != null)) {
                    base.Tables.Add(new RelatorioRegistroEventoDataSetDataTable(ds.Tables["RelatorioRegistroEventoDataSet"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RelatorioRegistroEventoDataSetDataTable _RelatorioRegistroEventoDataSet {
            get {
                return this.tableRelatorioRegistroEventoDataSet;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            RelatorioRegistroEventoDataSet cln = ((RelatorioRegistroEventoDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RelatorioRegistroEventoDataSet"] != null)) {
                    base.Tables.Add(new RelatorioRegistroEventoDataSetDataTable(ds.Tables["RelatorioRegistroEventoDataSet"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableRelatorioRegistroEventoDataSet = ((RelatorioRegistroEventoDataSetDataTable)(base.Tables["RelatorioRegistroEventoDataSet"]));
            if ((initTable == true)) {
                if ((this.tableRelatorioRegistroEventoDataSet != null)) {
                    this.tableRelatorioRegistroEventoDataSet.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "RelatorioRegistroEventoDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/RelatorioRegistroEventoDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRelatorioRegistroEventoDataSet = new RelatorioRegistroEventoDataSetDataTable();
            base.Tables.Add(this.tableRelatorioRegistroEventoDataSet);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_RelatorioRegistroEventoDataSet() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            RelatorioRegistroEventoDataSet ds = new RelatorioRegistroEventoDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void RelatorioRegistroEventoDataSetRowChangeEventHandler(object sender, RelatorioRegistroEventoDataSetRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RelatorioRegistroEventoDataSetDataTable : global::System.Data.TypedTableBase<RelatorioRegistroEventoDataSetRow> {
            
            private global::System.Data.DataColumn columnDataCadastroStr;
            
            private global::System.Data.DataColumn columnCodigoManifestacaoLiteral;
            
            private global::System.Data.DataColumn columnNomeTipoEvento;
            
            private global::System.Data.DataColumn columnOrigemStr;
            
            private global::System.Data.DataColumn columnNomeUnidadeGerida;
            
            private global::System.Data.DataColumn columnNomeResponsavelRetorno;
            
            private global::System.Data.DataColumn columnStatus;
            
            private global::System.Data.DataColumn columnStatusStr;
            
            private global::System.Data.DataColumn columnManifestanteStr;
            
            private global::System.Data.DataColumn columnTelefoneStr;
            
            private global::System.Data.DataColumn columnTipoManifestanteStr;
            
            private global::System.Data.DataColumn columnManifestanteAcompStr;
            
            private global::System.Data.DataColumn columnTelefoneAcompStr;
            
            private global::System.Data.DataColumn columnTipoManifestanteAcompStr;
            
            private global::System.Data.DataColumn columnDataOcorrenciaStr;
            
            private global::System.Data.DataColumn columnInfoEvento;
            
            private global::System.Data.DataColumn columnDataRetornoPacienteStr;
            
            private global::System.Data.DataColumn columnDataHoraAlteracaoStr;
            
            private global::System.Data.DataColumn columnNomeSetorEntidade;
            
            private global::System.Data.DataColumn columnDataRetornoUnidadeStr;
            
            private global::System.Data.DataColumn columnInfoRetornoPaciente;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RelatorioRegistroEventoDataSetDataTable() {
                this.TableName = "RelatorioRegistroEventoDataSet";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal RelatorioRegistroEventoDataSetDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected RelatorioRegistroEventoDataSetDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DataCadastroStrColumn {
                get {
                    return this.columnDataCadastroStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CodigoManifestacaoLiteralColumn {
                get {
                    return this.columnCodigoManifestacaoLiteral;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NomeTipoEventoColumn {
                get {
                    return this.columnNomeTipoEvento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OrigemStrColumn {
                get {
                    return this.columnOrigemStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NomeUnidadeGeridaColumn {
                get {
                    return this.columnNomeUnidadeGerida;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NomeResponsavelRetornoColumn {
                get {
                    return this.columnNomeResponsavelRetorno;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn StatusColumn {
                get {
                    return this.columnStatus;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn StatusStrColumn {
                get {
                    return this.columnStatusStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ManifestanteStrColumn {
                get {
                    return this.columnManifestanteStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TelefoneStrColumn {
                get {
                    return this.columnTelefoneStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TipoManifestanteStrColumn {
                get {
                    return this.columnTipoManifestanteStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ManifestanteAcompStrColumn {
                get {
                    return this.columnManifestanteAcompStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TelefoneAcompStrColumn {
                get {
                    return this.columnTelefoneAcompStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TipoManifestanteAcompStrColumn {
                get {
                    return this.columnTipoManifestanteAcompStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DataOcorrenciaStrColumn {
                get {
                    return this.columnDataOcorrenciaStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn InfoEventoColumn {
                get {
                    return this.columnInfoEvento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DataRetornoPacienteStrColumn {
                get {
                    return this.columnDataRetornoPacienteStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DataHoraAlteracaoStrColumn {
                get {
                    return this.columnDataHoraAlteracaoStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NomeSetorEntidadeColumn {
                get {
                    return this.columnNomeSetorEntidade;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DataRetornoUnidadeStrColumn {
                get {
                    return this.columnDataRetornoUnidadeStr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn InfoRetornoPacienteColumn {
                get {
                    return this.columnInfoRetornoPaciente;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RelatorioRegistroEventoDataSetRow this[int index] {
                get {
                    return ((RelatorioRegistroEventoDataSetRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RelatorioRegistroEventoDataSetRowChangeEventHandler RelatorioRegistroEventoDataSetRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RelatorioRegistroEventoDataSetRowChangeEventHandler RelatorioRegistroEventoDataSetRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RelatorioRegistroEventoDataSetRowChangeEventHandler RelatorioRegistroEventoDataSetRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RelatorioRegistroEventoDataSetRowChangeEventHandler RelatorioRegistroEventoDataSetRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddRelatorioRegistroEventoDataSetRow(RelatorioRegistroEventoDataSetRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RelatorioRegistroEventoDataSetRow AddRelatorioRegistroEventoDataSetRow(
                        string DataCadastroStr, 
                        string CodigoManifestacaoLiteral, 
                        string NomeTipoEvento, 
                        string OrigemStr, 
                        string NomeUnidadeGerida, 
                        string NomeResponsavelRetorno, 
                        string Status, 
                        string StatusStr, 
                        string ManifestanteStr, 
                        string TelefoneStr, 
                        string TipoManifestanteStr, 
                        string ManifestanteAcompStr, 
                        string TelefoneAcompStr, 
                        string TipoManifestanteAcompStr, 
                        string DataOcorrenciaStr, 
                        string InfoEvento, 
                        string DataRetornoPacienteStr, 
                        string DataHoraAlteracaoStr, 
                        string NomeSetorEntidade, 
                        string DataRetornoUnidadeStr, 
                        string InfoRetornoPaciente) {
                RelatorioRegistroEventoDataSetRow rowRelatorioRegistroEventoDataSetRow = ((RelatorioRegistroEventoDataSetRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DataCadastroStr,
                        CodigoManifestacaoLiteral,
                        NomeTipoEvento,
                        OrigemStr,
                        NomeUnidadeGerida,
                        NomeResponsavelRetorno,
                        Status,
                        StatusStr,
                        ManifestanteStr,
                        TelefoneStr,
                        TipoManifestanteStr,
                        ManifestanteAcompStr,
                        TelefoneAcompStr,
                        TipoManifestanteAcompStr,
                        DataOcorrenciaStr,
                        InfoEvento,
                        DataRetornoPacienteStr,
                        DataHoraAlteracaoStr,
                        NomeSetorEntidade,
                        DataRetornoUnidadeStr,
                        InfoRetornoPaciente};
                rowRelatorioRegistroEventoDataSetRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRelatorioRegistroEventoDataSetRow);
                return rowRelatorioRegistroEventoDataSetRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                RelatorioRegistroEventoDataSetDataTable cln = ((RelatorioRegistroEventoDataSetDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RelatorioRegistroEventoDataSetDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnDataCadastroStr = base.Columns["DataCadastroStr"];
                this.columnCodigoManifestacaoLiteral = base.Columns["CodigoManifestacaoLiteral"];
                this.columnNomeTipoEvento = base.Columns["NomeTipoEvento"];
                this.columnOrigemStr = base.Columns["OrigemStr"];
                this.columnNomeUnidadeGerida = base.Columns["NomeUnidadeGerida"];
                this.columnNomeResponsavelRetorno = base.Columns["NomeResponsavelRetorno"];
                this.columnStatus = base.Columns["Status"];
                this.columnStatusStr = base.Columns["StatusStr"];
                this.columnManifestanteStr = base.Columns["ManifestanteStr"];
                this.columnTelefoneStr = base.Columns["TelefoneStr"];
                this.columnTipoManifestanteStr = base.Columns["TipoManifestanteStr"];
                this.columnManifestanteAcompStr = base.Columns["ManifestanteAcompStr"];
                this.columnTelefoneAcompStr = base.Columns["TelefoneAcompStr"];
                this.columnTipoManifestanteAcompStr = base.Columns["TipoManifestanteAcompStr"];
                this.columnDataOcorrenciaStr = base.Columns["DataOcorrenciaStr"];
                this.columnInfoEvento = base.Columns["InfoEvento"];
                this.columnDataRetornoPacienteStr = base.Columns["DataRetornoPacienteStr"];
                this.columnDataHoraAlteracaoStr = base.Columns["DataHoraAlteracaoStr"];
                this.columnNomeSetorEntidade = base.Columns["NomeSetorEntidade"];
                this.columnDataRetornoUnidadeStr = base.Columns["DataRetornoUnidadeStr"];
                this.columnInfoRetornoPaciente = base.Columns["InfoRetornoPaciente"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnDataCadastroStr = new global::System.Data.DataColumn("DataCadastroStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataCadastroStr);
                this.columnCodigoManifestacaoLiteral = new global::System.Data.DataColumn("CodigoManifestacaoLiteral", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCodigoManifestacaoLiteral);
                this.columnNomeTipoEvento = new global::System.Data.DataColumn("NomeTipoEvento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomeTipoEvento);
                this.columnOrigemStr = new global::System.Data.DataColumn("OrigemStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOrigemStr);
                this.columnNomeUnidadeGerida = new global::System.Data.DataColumn("NomeUnidadeGerida", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomeUnidadeGerida);
                this.columnNomeResponsavelRetorno = new global::System.Data.DataColumn("NomeResponsavelRetorno", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomeResponsavelRetorno);
                this.columnStatus = new global::System.Data.DataColumn("Status", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStatus);
                this.columnStatusStr = new global::System.Data.DataColumn("StatusStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStatusStr);
                this.columnManifestanteStr = new global::System.Data.DataColumn("ManifestanteStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnManifestanteStr);
                this.columnTelefoneStr = new global::System.Data.DataColumn("TelefoneStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTelefoneStr);
                this.columnTipoManifestanteStr = new global::System.Data.DataColumn("TipoManifestanteStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipoManifestanteStr);
                this.columnManifestanteAcompStr = new global::System.Data.DataColumn("ManifestanteAcompStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnManifestanteAcompStr);
                this.columnTelefoneAcompStr = new global::System.Data.DataColumn("TelefoneAcompStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTelefoneAcompStr);
                this.columnTipoManifestanteAcompStr = new global::System.Data.DataColumn("TipoManifestanteAcompStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipoManifestanteAcompStr);
                this.columnDataOcorrenciaStr = new global::System.Data.DataColumn("DataOcorrenciaStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataOcorrenciaStr);
                this.columnInfoEvento = new global::System.Data.DataColumn("InfoEvento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInfoEvento);
                this.columnDataRetornoPacienteStr = new global::System.Data.DataColumn("DataRetornoPacienteStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataRetornoPacienteStr);
                this.columnDataHoraAlteracaoStr = new global::System.Data.DataColumn("DataHoraAlteracaoStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataHoraAlteracaoStr);
                this.columnNomeSetorEntidade = new global::System.Data.DataColumn("NomeSetorEntidade", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomeSetorEntidade);
                this.columnDataRetornoUnidadeStr = new global::System.Data.DataColumn("DataRetornoUnidadeStr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataRetornoUnidadeStr);
                this.columnInfoRetornoPaciente = new global::System.Data.DataColumn("InfoRetornoPaciente", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInfoRetornoPaciente);
                this.ExtendedProperties.Add("Generator_TablePropName", "_RelatorioRegistroEventoDataSet");
                this.ExtendedProperties.Add("Generator_UserTableName", "RelatorioRegistroEventoDataSet");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RelatorioRegistroEventoDataSetRow NewRelatorioRegistroEventoDataSetRow() {
                return ((RelatorioRegistroEventoDataSetRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RelatorioRegistroEventoDataSetRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(RelatorioRegistroEventoDataSetRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RelatorioRegistroEventoDataSetRowChanged != null)) {
                    this.RelatorioRegistroEventoDataSetRowChanged(this, new RelatorioRegistroEventoDataSetRowChangeEvent(((RelatorioRegistroEventoDataSetRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RelatorioRegistroEventoDataSetRowChanging != null)) {
                    this.RelatorioRegistroEventoDataSetRowChanging(this, new RelatorioRegistroEventoDataSetRowChangeEvent(((RelatorioRegistroEventoDataSetRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RelatorioRegistroEventoDataSetRowDeleted != null)) {
                    this.RelatorioRegistroEventoDataSetRowDeleted(this, new RelatorioRegistroEventoDataSetRowChangeEvent(((RelatorioRegistroEventoDataSetRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RelatorioRegistroEventoDataSetRowDeleting != null)) {
                    this.RelatorioRegistroEventoDataSetRowDeleting(this, new RelatorioRegistroEventoDataSetRowChangeEvent(((RelatorioRegistroEventoDataSetRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveRelatorioRegistroEventoDataSetRow(RelatorioRegistroEventoDataSetRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                RelatorioRegistroEventoDataSet ds = new RelatorioRegistroEventoDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RelatorioRegistroEventoDataSetDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RelatorioRegistroEventoDataSetRow : global::System.Data.DataRow {
            
            private RelatorioRegistroEventoDataSetDataTable tableRelatorioRegistroEventoDataSet;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal RelatorioRegistroEventoDataSetRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRelatorioRegistroEventoDataSet = ((RelatorioRegistroEventoDataSetDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DataCadastroStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.DataCadastroStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataCadastroStr\' in table \'RelatorioRegistroEventoDataSet\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.DataCadastroStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CodigoManifestacaoLiteral {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.CodigoManifestacaoLiteralColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CodigoManifestacaoLiteral\' in table \'RelatorioRegistroEvent" +
                                "oDataSet\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.CodigoManifestacaoLiteralColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NomeTipoEvento {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.NomeTipoEventoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomeTipoEvento\' in table \'RelatorioRegistroEventoDataSet\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.NomeTipoEventoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string OrigemStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.OrigemStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OrigemStr\' in table \'RelatorioRegistroEventoDataSet\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.OrigemStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NomeUnidadeGerida {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.NomeUnidadeGeridaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomeUnidadeGerida\' in table \'RelatorioRegistroEventoDataSet" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.NomeUnidadeGeridaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NomeResponsavelRetorno {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.NomeResponsavelRetornoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomeResponsavelRetorno\' in table \'RelatorioRegistroEventoDa" +
                                "taSet\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.NomeResponsavelRetornoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Status {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.StatusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Status\' in table \'RelatorioRegistroEventoDataSet\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.StatusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string StatusStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.StatusStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'StatusStr\' in table \'RelatorioRegistroEventoDataSet\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.StatusStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ManifestanteStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.ManifestanteStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ManifestanteStr\' in table \'RelatorioRegistroEventoDataSet\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.ManifestanteStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TelefoneStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.TelefoneStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TelefoneStr\' in table \'RelatorioRegistroEventoDataSet\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.TelefoneStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TipoManifestanteStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.TipoManifestanteStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TipoManifestanteStr\' in table \'RelatorioRegistroEventoDataS" +
                                "et\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.TipoManifestanteStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ManifestanteAcompStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.ManifestanteAcompStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ManifestanteAcompStr\' in table \'RelatorioRegistroEventoData" +
                                "Set\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.ManifestanteAcompStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TelefoneAcompStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.TelefoneAcompStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TelefoneAcompStr\' in table \'RelatorioRegistroEventoDataSet\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.TelefoneAcompStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TipoManifestanteAcompStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.TipoManifestanteAcompStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TipoManifestanteAcompStr\' in table \'RelatorioRegistroEvento" +
                                "DataSet\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.TipoManifestanteAcompStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DataOcorrenciaStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.DataOcorrenciaStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataOcorrenciaStr\' in table \'RelatorioRegistroEventoDataSet" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.DataOcorrenciaStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string InfoEvento {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.InfoEventoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'InfoEvento\' in table \'RelatorioRegistroEventoDataSet\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.InfoEventoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DataRetornoPacienteStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.DataRetornoPacienteStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataRetornoPacienteStr\' in table \'RelatorioRegistroEventoDa" +
                                "taSet\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.DataRetornoPacienteStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DataHoraAlteracaoStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.DataHoraAlteracaoStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataHoraAlteracaoStr\' in table \'RelatorioRegistroEventoData" +
                                "Set\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.DataHoraAlteracaoStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NomeSetorEntidade {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.NomeSetorEntidadeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomeSetorEntidade\' in table \'RelatorioRegistroEventoDataSet" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.NomeSetorEntidadeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DataRetornoUnidadeStr {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.DataRetornoUnidadeStrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataRetornoUnidadeStr\' in table \'RelatorioRegistroEventoDat" +
                                "aSet\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.DataRetornoUnidadeStrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string InfoRetornoPaciente {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioRegistroEventoDataSet.InfoRetornoPacienteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'InfoRetornoPaciente\' in table \'RelatorioRegistroEventoDataS" +
                                "et\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioRegistroEventoDataSet.InfoRetornoPacienteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDataCadastroStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.DataCadastroStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDataCadastroStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.DataCadastroStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCodigoManifestacaoLiteralNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.CodigoManifestacaoLiteralColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCodigoManifestacaoLiteralNull() {
                this[this.tableRelatorioRegistroEventoDataSet.CodigoManifestacaoLiteralColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNomeTipoEventoNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.NomeTipoEventoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNomeTipoEventoNull() {
                this[this.tableRelatorioRegistroEventoDataSet.NomeTipoEventoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOrigemStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.OrigemStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOrigemStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.OrigemStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNomeUnidadeGeridaNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.NomeUnidadeGeridaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNomeUnidadeGeridaNull() {
                this[this.tableRelatorioRegistroEventoDataSet.NomeUnidadeGeridaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNomeResponsavelRetornoNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.NomeResponsavelRetornoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNomeResponsavelRetornoNull() {
                this[this.tableRelatorioRegistroEventoDataSet.NomeResponsavelRetornoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsStatusNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.StatusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetStatusNull() {
                this[this.tableRelatorioRegistroEventoDataSet.StatusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsStatusStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.StatusStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetStatusStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.StatusStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsManifestanteStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.ManifestanteStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetManifestanteStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.ManifestanteStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTelefoneStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.TelefoneStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTelefoneStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.TelefoneStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTipoManifestanteStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.TipoManifestanteStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTipoManifestanteStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.TipoManifestanteStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsManifestanteAcompStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.ManifestanteAcompStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetManifestanteAcompStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.ManifestanteAcompStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTelefoneAcompStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.TelefoneAcompStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTelefoneAcompStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.TelefoneAcompStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTipoManifestanteAcompStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.TipoManifestanteAcompStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTipoManifestanteAcompStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.TipoManifestanteAcompStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDataOcorrenciaStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.DataOcorrenciaStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDataOcorrenciaStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.DataOcorrenciaStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsInfoEventoNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.InfoEventoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetInfoEventoNull() {
                this[this.tableRelatorioRegistroEventoDataSet.InfoEventoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDataRetornoPacienteStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.DataRetornoPacienteStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDataRetornoPacienteStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.DataRetornoPacienteStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDataHoraAlteracaoStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.DataHoraAlteracaoStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDataHoraAlteracaoStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.DataHoraAlteracaoStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNomeSetorEntidadeNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.NomeSetorEntidadeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNomeSetorEntidadeNull() {
                this[this.tableRelatorioRegistroEventoDataSet.NomeSetorEntidadeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDataRetornoUnidadeStrNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.DataRetornoUnidadeStrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDataRetornoUnidadeStrNull() {
                this[this.tableRelatorioRegistroEventoDataSet.DataRetornoUnidadeStrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsInfoRetornoPacienteNull() {
                return this.IsNull(this.tableRelatorioRegistroEventoDataSet.InfoRetornoPacienteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetInfoRetornoPacienteNull() {
                this[this.tableRelatorioRegistroEventoDataSet.InfoRetornoPacienteColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class RelatorioRegistroEventoDataSetRowChangeEvent : global::System.EventArgs {
            
            private RelatorioRegistroEventoDataSetRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RelatorioRegistroEventoDataSetRowChangeEvent(RelatorioRegistroEventoDataSetRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RelatorioRegistroEventoDataSetRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591